CREATE DATABASE `CafeSuite`;
USE `CafeSuite`;

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `AccountBill` (
  `ID` int(11) NOT NULL auto_increment,
  `UserName` varchar(255) default NULL,
  `Time` datetime default NULL,
  `ProductName` varchar(255) default NULL,
  `ProductID` varchar(255) default NULL,
  `ProductUnit` varchar(255) default NULL,
  `ProductVAT` varchar(255) default NULL,
  `ProductType` varchar(255) default NULL,
  `Count` int(11) default '0',
  `Price` decimal(19,4) default '0.0000',
  `Operator` varchar(255) default NULL,
  `LocationId` int(11) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ID` (`ID`),
  KEY `ProductID` (`ProductID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `AccountHistory` (
  `ID` int(11) NOT NULL auto_increment,
  `UserName` varchar(255) default NULL,
  `State` int(11) default '0',
  `Type` int(11) default '0',
  `AccountType` int(11) default '0',
  `Time` datetime default NULL,
  `StartTime` datetime default NULL,
  `Workstation` varchar(255) default NULL,
  `Period` int(11) default '0',
  `Charge` decimal(19,4) default '0.0000',
  `Price` decimal(19,4) default '0.0000',
  `Debt` decimal(19,4) default '0.0000',
  `Points` int(11) default '0',
  `Rates` varchar(255) default NULL,
  `Operator` varchar(255) default NULL,
  `Reset` tinyint(4) default '0',
  `LocationId` int(11) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `Accounts` (
  `ID` int(11) NOT NULL auto_increment,
  `Username` varchar(255) NOT NULL,
  `Barcode` varchar(255) default NULL,
  `SmartCard` text,
  `Password` varchar(255) default NULL,
  `AccountType` int(11) default '0',
  `AccountGroup` varchar(255) default NULL,
  `TotalTime` int(11) default '0',
  `UsedTime` int(11) default NULL,
  `LeftTime` int(11) default NULL,
  `SpentTime` int(11) default NULL,
  `BonusTime` int(11) default '0',
  `TotalCash` decimal(19,4) default '0.0000',
  `UsedCash` decimal(19,4) default '0.0000',
  `LeftCash` decimal(19,4) default NULL,
  `SpentCash` decimal(19,4) default NULL,
  `SetupFee` decimal(19,4) default NULL,
  `Debt` decimal(19,4) default '0.0000',
  `MaxDebt` decimal(19,4) default NULL,
  `Points` int(11) default '0',
  `TotalPoints` int(11) default '0',
  `Created` datetime default NULL,
  `FirstUsed` datetime default NULL,
  `LastUsed` datetime default NULL,
  `ValidSince` int(11) default NULL,
  `ValidFromDate` datetime default NULL,
  `ValidToDate` datetime default NULL,
  `Expires` datetime default NULL,
  `ValidFromTime` datetime default NULL,
  `ValidToTime` datetime default NULL,
  `ValidForDays` int(11) default NULL,
  `ValidDays` tinyint(4) default '0',
  `MaxUsagePeriod` int(11) default '1440',
  `MaxUsageInPeriod` int(11) default '24',
  `AllowChangePasswd` tinyint(4) default '0',
  `ForceChangePasswd` tinyint(4) default '0',
  `AllowLogin` tinyint(4) default '0',
  `NoPassword` tinyint(4) default '0',
  `UseWorkstationRates` tinyint(4) default '0',
  `AccumulateTime` tinyint(4) default '0',
  `Rates` varchar(255) default NULL,
  `FirstName` varchar(255) default NULL,
  `MiddleName` varchar(50) default NULL,
  `LastName` varchar(255) default NULL,
  `Title` varchar(50) default NULL,
  `Phone` varchar(255) default NULL,
  `Mobile` varchar(255) default NULL,
  `Fax` varchar(255) default NULL,
  `Address` text,
  `City` varchar(50) default NULL,
  `Country` varchar(50) default NULL,
  `Email` varchar(255) default NULL,
  `Gender` int(11) default '-1',
  `Birthday` datetime default NULL,
  `Comment` text,
  `Description` text,
  `Custom1` varchar(255) default NULL,
  `Custom2` varchar(255) default NULL,
  `Custom3` varchar(255) default NULL,
  `Custom4` varchar(255) default NULL,
  `Custom5` varchar(255) default NULL,
  `Custom6` varchar(255) default NULL,
  `LoginMsg` text,
  `ProductsDiscount` int(11) default NULL,
  `ServicesDiscount` int(11) default NULL,
  `CollectPoints` tinyint(4) default '0',
  `LimitDebt` tinyint(4) default '0',
  `ShowLoginMsg` int(11) default NULL,
  `LocationId` int(11) default NULL,
  `Machine` varchar(255) default NULL,
  `AutoLimit` int(11) default NULL,
  `LimitPrintouts` tinyint(4) default '0',
  `MaxPrintouts` int(11) default NULL,
  `NoAutoDelete` tinyint(4) default '0',
  `Updated` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `Locked` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `UserName` (`Username`),
  KEY `Barcode` (`Barcode`),
  KEY `LocationId` (`LocationId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;

CREATE TABLE IF NOT EXISTS `Locations` (
  `LocationID` int(11) NOT NULL auto_increment,
  `Name` varchar(255) default NULL,
  `Address` text,
  `Desc` text,
  `Currency` varchar(3) default NULL,
  PRIMARY KEY  (`LocationID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS `Sales` (
  `ID` int(11) NOT NULL auto_increment,
  `OrderID` int(11) default NULL,
  `SessionID` int(11) default NULL,
  `ReceiptID` int(11) default NULL,
  `OrderTime` datetime default NULL,
  `OrderState` int(11) default NULL,
  `OrderType` int(11) default NULL,
  `ProductName` varchar(255) default NULL,
  `ProductUnit` varchar(50) default NULL,
  `ProductID` varchar(255) default NULL,
  `NettoPrice` decimal(19,4) default NULL,
  `Count` int(11) default NULL,
  `Charge` decimal(19,4) default NULL,
  `MinutesCharge` int(11) default NULL,
  `Discount` int(11) default NULL,
  `Tax1` int(11) default NULL,
  `Tax2` int(11) default NULL,
  `Operator` varchar(255) default NULL,
  `ShiftID` int(11) default NULL,
  `Account` varchar(255) default NULL,
  `Workstation` varchar(255) default NULL,
  `Location` varchar(255) default NULL,
  `LocationId` int(11) default NULL,
  `Machine` varchar(255) default NULL,
  `Currency` varchar(3) default NULL,
  UNIQUE KEY `ID` (`ID`),
  KEY `LocationId` (`LocationId`),
  KEY `OrderID` (`OrderID`),
  KEY `ReceiptID` (`ReceiptID`),
  KEY `SessionID` (`SessionID`),
  KEY `ShiftID` (`ShiftID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=154 ;
